gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power

cpu_stats
cpu_temp
cpu_power
cpu_mhz

vram
ram
# ram_temp
swap

battery
battery_watt
battery_time

fps
frametime

engine_short_names
vulkan_driver
wine

histogram
graphs=

font_size=16
font_file=/run/current-system/sw/share/X11/fonts/FiraMonoNerdFont-Medium.otf

text_outline

round_corners=0

hud_no_margin
hud_compact

no_display
