[Personal Gmail]
source            = imaps+xoauth2://joe.bearchell%40gmail.com@imap.gmail.com:993
outgoing          = smtps+xoauth2://joe.bearchell%40gmail.com@smtp.gmail.com:465
default           = INBOX
from              = Joe Bearchell <joe.bearchell@gmail.com>
cache-headers     = true

folders-sort = INBOX
postpone     = [Gmail]/Drafts

pgp-auto-sign     = true
pgp-self-encrypt  = true

source-cred-cmd   = 'oama access joebearchell@gmail.com'
outgoing-cred-cmd = 'oama access joebearchell@gmail.com'

[Sheffield Gmail]
source            = imaps+xoauth2://jrbearchell1%40sheffield.ac.uk@imap.gmail.com:993
outgoing          = smtps+xoauth2://jrbearchell1%40sheffield.ac.uk@smtp.gmail.com:465
default           = INBOX
from              = Joe Bearchell <jrbearchell1@sheffield.ac.uk>
cache-headers     = true

folders-sort = INBOX
postpone     = [Gmail]/Drafts

pgp-auto-sign     = false
pgp-self-encrypt  = true

source-cred-cmd   = 'oama access jrbearchell1@sheffield.ac.uk'
outgoing-cred-cmd = 'oama access jrbearchell1@sheffield.ac.uk'
