#!/usr/bin/env sh

if grep 165 /tmp/refresh-rate
then
	hyprctl keyword monitor \
		$(hyprctl monitors -j | jq -r '.[0]."name"'),\
		$(hyprctl monitors -j | jq -r '.[0]."width"')x$(hyprctl monitors -j | jq -r '.[0]."height"')@60,\
		auto,1
	echo 60 > /tmp/refresh-rate
else
	hyprctl keyword monitor \
		$(hyprctl monitors -j | jq -r '.[0]."name"'),\
		$(hyprctl monitors -j | jq -r '.[0]."width"')x$(hyprctl monitors -j | jq -r '.[0]."height"')@165,\
		auto,1
	echo 165 > /tmp/refresh-rate
fi
