#!/usr/bin/env sh

if [ "$(hostname)" == "karl" ]
then
	export DRI_PRIME=pci-0000_01_00_0!
	export DXVK_FILTER_DEVICE_NAME="NVIDIA"
	export __GLX_VENDOR_LIBRARY_NAME=nvidia
	export LIBGL_ALWAYS_SOFTWARE=0
	export __NV_PRIME_RENDER_OFFLOAD=1
	export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
	export VK_DRIVER_FILES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json
	export __VK_LAYER_NV_optimus=NVIDIA_only

	exec "$@"
fi
