#!/usr/bin/env sh

cd "$(dirname $0)/.."

[ ! -d ~/.config/nvim ] && ln -st ~/.config "$(realpath ./nvim)"
[ ! -d ~/.config/sway ] && ln -st ~/.config "$(realpath ./sway)"
[ ! -d ~/.config/waybar ] && ln -st ~/.config "$(realpath ./waybar)"
[ ! -d ~/.config/mako ] && ln -st ~/.config "$(realpath ./mako)"
[ ! -d ~/.config/alacritty ] && ln -st ~/.config "$(realpath ./alacritty)"
[ ! -d ~/scripts ] && ln -st ~ "$(realpath ./scripts)"
[ ! -f ~/.zshrc ] && ln -s ~/.zshrc "$(realpath .zshrc)"
[ ! -f ~/.tmux.conf ] && ln -s ~/.tmux.conf "$(realpath .tmux.conf)" 
