#!/usr/bin/env sh

if [ -e /tmp/inhibitor ] && [ "$1" == "lid" ]
then
	lock_cmd=
else
	lock_cmd="hyprlock"
fi

if pactl get-sink-mute @DEFAULT_SINK@ | grep no; then
	playerctl pause
	pactl set-sink-mute @DEFAULT_SINK@ true

	if [ "$1" == "lid" ];
	then
		systemctl sleep
		$lock_cmd
	else
		$lock_cmd
	fi
	pactl set-sink-mute @DEFAULT_SINK@ false
else
	playerctl pause
	$lock_cmd
fi
