#!/usr/bin/env sh

if pactl get-sink-mute @DEFAULT_SINK@ | grep no; then
	playerctl pause
	pactl set-sink-mute @DEFAULT_SINK@ true
	if [ "$1" == "lid" ];
	then
		systemctl sleep
		hyprlock
	else
		hyprlock
	fi
	pactl set-sink-mute @DEFAULT_SINK@ false
else
	playerctl pause
	hyprlock
fi
