#!/usr/bin/env sh

ARGS=$(echo $@ | sed "s/$1//")

export IS_NIX_SHELL=1
export NIXPKGS_ALLOW_UNFREE=1

case $1 in
	shell )
		if echo $ARGS | grep "\-c" &>/dev/null
		then
			nom shell --impure $ARGS
		else
			nom shell --impure $ARGS -c zsh
		fi;;
	proxychains-shell )
		export IS_TOR_SHELL=1

		if echo $ARGS | grep "\-c" &>/dev/null
		then
			proxychains4 -q nom shell --impure $ARGS
		else
			proxychains4 -q nom shell --impure $ARGS -c zsh
		fi;;
	run )
		nix run --impure $ARGS;;
	proxychains-run )
		export IS_TOR_SHELL=1

		proxychains4 -q nix run --impure $ARGS;;
	develop )
		if echo $ARGS | grep "\-c" &>/dev/null
		then
			nom develop --impure $ARGS
		else
			nom develop --impure $ARGS -c zsh
		fi;;
	proxychains-develop )
		export IS_TOR_SHELL=1

		if echo $ARGS | grep "\-c" &>/dev/null || echo $ARGS | grep "\#" &>/dev/null
		then
			proxychains4 -q nom develop --impure $ARGS
		else
			proxychains4 -q nom develop --impure $ARGS -c zsh
		fi;;
esac
