#!/bin/env zsh

MEDIA_STATUS=$(playerctl status 2>/dev/null || echo "not playing")

if [ $MEDIA_STATUS = "Playing" ]
then
	# playerctl pause
	playerctl volume 0.5-
fi

play_cmd () {
	paplay --volume=49152 ~/.dotfiles/dunst/notification-sound.mp3
}

sleep_cmd () {
	sleep 0.25
}


if [ -z $(echo $@ | rev | cut -f1 -d\  | rev | grep CRITICAL) ]
then
else
	play_cmd & sleep_cmd
	play_cmd & sleep_cmd
fi

if [ -z $(echo $@ | rev | cut -f1 -d\  | rev | grep NORMAL) ]
then
else
	play_cmd & sleep_cmd
fi

play_cmd & sleep 1

if [ $MEDIA_STATUS = "Playing" ]
then
	# playerctl play
	playerctl volume 0.5+
fi
