#!/usr/bin/env zsh

lockfile="/tmp/dunst-${DUNST_URGENCY}-notification-lock"

play_cmd () {
	file=~/.dotfiles/dunst/notification-${1}.ogg
	[ -e $file ] && paplay --volume=49152 $file
}

sleep_cmd () {
	sleep 0.25
}

[ -e $lockfile ] && exit

touch $lockfile

case "$DUNST_URGENCY" in
	CRITICAL)
		play_cmd critical
		;;
	NORMAL)
		play_cmd normal
		;;
	LOW)
		play_cmd low
		;;
esac

rm $lockfile
