#!/bin/sh

if [ $1 = "reset" ]; then
	pid=$(pidof swaybg)
	swaybg -i ~/.config/sway/wallpaper.jpg -m fill &
	sleep 1
	kill $pid
	exit
fi

key=$(cat ~/scripts/apod-api-key)
date=$(
	shuf -n1 \
	-i $(date -d '2000-01-01' '+%s')-$(date '+%s') \
	| xargs -I{} date -d '@{}' +%Y-%m-%d
)

url=https://api.nasa.gov/planetary/apod\?api_key=$key\&date=$date\&thumbs=true
data=$(curl -Ss $url)
url=$(echo $data | jq -r .hdurl || .thumbnail_url)

if [ $url = "null" ]; then
	echo $url
	echo $data
	exit 1
fi

ext=$(echo $url | awk -F. '{print $NF}')

[ -f /tmp/apod.$ext ] && rm /tmp/apod.$ext
curl -Sso /tmp/apod.$ext $url

IFS=, read w h < <(cat /sys/class/graphics/*/virtual_size)
padding=20
ffmpeg -y -i /tmp/apod.$ext \
	-vf "scale=iw*min($w/iw\,$h/ih):ih*min($w/iw\,$h/ih),pad=$w:$h:($w-iw)/2:($h-ih)/2:#303446,pad=iw+$padding*2:ih+$padding*2:$padding:$padding:#303446" \
	/tmp/apod.$ext

pid=$(pidof swaybg)
swaybg -i /tmp/apod.$ext -m fill &
sleep 1
kill $pid
