#!/usr/bin/env sh
hyprpm reload
sleep 1
hyprctl dispatch exec 'ghostty --class="wallpaper" --title="wallpaper" --background="#000000" --font-size=8 --background-opacity=1 -e "nice -n 21 /home/redstonetrail/projects/zmatrix/zig-out/bin/zmatrix -i -d 400"'
