#!/usr/bin/env sh

if [ "$(hostname)" == "karl" ]
then
	export DXVK_FILTER_DEVICE_NAME="llvmpipe"
	export __GLX_VENDOR_LIBRARY_NAME=mesa
	export LIBGL_ALWAYS_SOFTWARE=1
	export __NV_PRIME_RENDER_OFFLOAD=0
	export VK_DRIVER_FILES=/run/opengl-driver/share/vulkan/icd.d/lvp_icd.x86_64.json
	export __VK_LAYER_NV_optimus=non_NVIDIA_only

	exec "$@"
fi
