#!/usr/bin/env sh

for artist in *
do
	printf "albums for $artist\n"
	cd $artist
	for album in *
	do
		printf "\ttracks for $album\n"
		cd $album

		for song in *.opus
		do
			track_number=$(( $(echo $song | cut -d\- -f1 | bc) + 1 ))
			total_tracks=$(ls -1 *.opus | grep -c .\*)
			# id3v2 -t $song -a $artist -A $album -T $(( $(echo $song | cut -d\- -f1 | bc) + 1 ))/$(ls -1 *.opus | grep -c .\*) $song
			opustags -i\
				-a ARTIST=$artist\
				-a TITLE=$song\
				-a ALBUM=$album\
				-a TRACKNUMBER="${track_number}/${total_tracks}"\
				$song
		done
		cd ..
	done
	cd ..
done
