#!/usr/bin/env sh

set -e

HOST=$(hostname)

require_specialisation () {
	specialisation_file=/etc/specialisation

	SPECIALISATION=none

	if [ -e "$specialisation_file" ]
	then
		SPECIALISATION=$(</etc/specialisation)
	fi

	if echo $SPECIALISATION | grep -E '^'"$1" &>/dev/null
	then
		true
	else
		echo not supported for host \"$HOST\" with specialisation \"$SPECIALISATION\"
		exit
	fi
}

case $HOST in
	karl)
		dgpu_accepted_specialisations='vfio-maxxing|none'

		case $1 in
			nvme1)
				PCI_DOMAIN=0000
				PCI_BUS=07
				PCI_SLOT=00
				PCI_FUNC=0

				NORMAL_DRIVER=nvme
				;;
			dgpu)
				if require_specialisation "$dgpu_accepted_specialisations"
				then
					$0 dgpu-video $2
					$0 dgpu-audio $2

					exit
				fi
				;;
			dgpu-video)
				if require_specialisation "$dgpu_accepted_specialisations"
				then
					PCI_DOMAIN=0000
					PCI_BUS=01
					PCI_SLOT=00
					PCI_FUNC=0

					NORMAL_DRIVER=nvidia
				fi
				;;
			dgpu-audio)
				if require_specialisation "$dgpu_accepted_specialisations"
				then
					PCI_DOMAIN=0000
					PCI_BUS=01
					PCI_SLOT=00
					PCI_FUNC=1

					NORMAL_DRIVER=snd_hda_intel
				fi
				;;
		esac
		;;
	*)
		echo not supported for host \"$HOST\"
		exit
		;;
esac

case $2 in
	detach)
		echo performing pre-detachment actions

		case $1 in
			nvme1)
				if sudo fuser -m /dev/disk/by-id/nvme-Micron_2210_MTFDHBA512QFD_20452B678873-part*
				then
					echo device in use! refusing to detach
					exit
				else
					echo confirmed device is not in use
				fi

				set +e
				sudo umount /windows/boot
				sudo umount /windows/root
				set -e
				;;
			dgpu-video)
				if sudo fuser -v /dev/nvidia*
				then
					echo device in use! refusing to detach
					exit
				else
					echo confirmed device is not in use
				fi
				;;
		esac


		echo detaching device $1 from host for vfio

		sudo modprobe vfio
		sudo modprobe vfio_iommu_type1
		sudo modprobe vfio_pci

		sudo virsh nodedev-detach pci_${PCI_DOMAIN}_${PCI_BUS}_${PCI_SLOT}_${PCI_FUNC}
		;;
	attach)
		echo attaching device $1 to host from vfio

		sudo virsh nodedev-reattach pci_${PCI_DOMAIN}_${PCI_BUS}_${PCI_SLOT}_${PCI_FUNC}

		echo performing post-attachment actions

		case $1 in
			nvme1)
				sleep 1

				sudo mount /windows/boot
				sudo mount /windows/root
				;;
		esac
		;;
esac
